### ISSUE TITLE
On-Hold Calls/Pickup Groups

### ISSUE THREAD

**Issue by AdBeg** [ringcentral/ringcentral-embeddable-electron-app#10]
I can see we can now interact with active calls on other devices which is great.  If I click on an active call (e.g. one that is active on the mobile app) I can put it on hold but can't seem to then be able to pick it up from the webphone.  If I try putting it on hold on the mobile device first it tells me that the call is already held elsewhere and to release it there first.  Basically what I am trying to do is put a call on hold on the mobile app and then pick it up via the webphone on my Linux desktop.  Should it work this way? 

Also for a future feature request could you make it so I can pick up something from a parked location? If you try to call the parked location extension you get a message saying "Extension is not available" even though it is.

Cheers for your help and also great work so far! Saved me lots of hassle trying to get this working for Linux users.

**Comment by embbnux** [comment]
Hi, @AdBeg Thanks so much for feedback. Seems there are issues in active call hold feature. It should works as expect. I will check with my colleagues.

Park call feature is in our backlog, I will check with PM about it. 

And very happy that this app is useful for you.

**Comment by AdBeg** [comment]
That's great.  Thanks @embbnux!

**Comment by embbnux** [comment]
@AdBeg We have updated the app to support to pick a parked call. You can try it after reopening the app.

**Comment by AdBeg** [comment]
Cheers @embbnux. Just tried this by dialling the parked location (e.g. *801) and it now connects the calls but just gives an engaged tone.  Tried the same process on the mobile app and it works fine there.  Any ideas?

**Comment by embbnux** [comment]
@AdBeg Can you go to this page https://ringcentral.github.io/ringcentral-embeddable/app.html login and try again to dial parked location, and provides logs as this:
![image](https://user-images.githubusercontent.com/7036536/61602469-3361be80-ac6c-11e9-9966-bd4ba752f007.png)
I just tried it, and works in my side. So need some logs from your side to track issue.

**Comment by embbnux** [comment]
For the hold issue: some messages from unhold API https://developers.ringcentral.com/api-reference/Call-Control/unholdCallParty 

> There is a known limitation for Hold API - hold via REST API doesn't work with hold placed via RingCentral apps or HardPhone. It means that if you muted participant via Call Control API and RingCentral Desktop app, then you need to unhold both endpoints to remove Hold Music and bring media back.

Need to wait the API to support it.

**Comment by AdBeg** [comment]
> @AdBeg Can you go to this page https://ringcentral.github.io/ringcentral-embeddable/app.html login and try again to dial parked location, and provides logs as this:
> ![image](https://user-images.githubusercontent.com/7036536/61602469-3361be80-ac6c-11e9-9966-bd4ba752f007.png)
> I just tried it, and works in my side. So need some logs from your side to track issue.

@embbnux sorry for the VERY late reply.  Totally understand about the Hold API.  I'll keep a lookout.  

In terms of the parked call pickup, what are you dialling to retrieve it?  If I dial the pickup group I get a message saying the group does not support calls (which looking at the documentation is how it should behave).  Just intrigued as to what you dialled to get the parked call back on the webphone as I cant seem to manage it.

Cheers,

Adam

**Comment by embbnux** [comment]
@AdBeg Sorry for missing last message. Do you still need it?
From my understanding, you want to pickup a parked call?  It should work by dialing "*1234", "1212" is the number that provided when user park the call.

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
