### ISSUE TITLE
receive inbound calls

### ISSUE THREAD

**Issue by noahfriedman** [ringcentral/ringcentral-embeddable-electron-app#11]
This app seems to do everything except receive voip calls.  I can even make outbound calls using a usb headset.  But no matter what I try, I can't get it to receive inbound calls.  Is this even possible?

(Update: ok, it did seem to work once this afternoon, but it's very unreliable.  And the admin portal still shows my status as "offline" even now.)

**Comment by embbnux** [comment]
Hi, @noahfriedman It should show inbound call. This may be a bug.  Sometime with poor network, it can't get inbound call.  Could you try its web version https://ringcentral.github.io/ringcentral-embeddable/ , and provide network HAR file when you can't get incoming call. So we can track the issue.

And I am not sure you are talking about presence status or sip device status.

For presence status, you can update your status in app setting page.
![image](https://user-images.githubusercontent.com/7036536/64675941-f31e0000-d4a6-11e9-9b5b-0aad5426c116.png)

For sip device status, this app is registered as web sip device. And status in admin portal doesn't include web sip device.

**Comment by noahfriedman** [comment]
Inbound calls are working, it turns out; the case that's not working is when someone tries my 4-digit extension from within a PBX that my number used to belong to, so I think that's a PBX problem (strangely, using my full 10-digit number works even from the PBX, go figure).  Sorry for the false alarm; it took a day to isolate this.

Status in the admin portal: Ok, I guess the entry that shows me offline is from the windows desktop app I used briefly.  Thanks about the clarification about web sip devices.

I think you can close this as invalid.

**Comment by embbnux** [comment]
Thanks @noahfriedman,  closed as invalid
