### ISSUE TITLE
Icon does not show on task bar

### ISSUE THREAD

**Issue by ajaysimha** [ringcentral/ringcentral-embeddable-electron-app#18]
Hi,

I'm first of all grateful that this actually works.
I'm using the Appimage as I'm running Fedora 32.

While functionality is fine, I see a black window on the task bar. How can I change that?

Thanks
Ajay

**Comment by embbnux** [comment]
Hi Ajay
I am not familiar with Fedora. But I guess there are something wrong in AppImage packager. https://github.com/AppImage/AppImageKit/issues/346
I will try to fix it.
Thanks  so much for feedback

**Comment by ajaysimha** [comment]
Thank you

**Comment by embbnux** [comment]
link related issue https://github.com/electron-userland/electron-builder/issues/2577

**Comment by embbnux** [comment]
Hi @ajaysimha, we have released 0.1.3 to fix this issue. Can you help to test it in Fedora?

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen.
