### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by yanike** [ringcentral/ringcentral-embeddable-electron-app#19]
// For new windows not to have menu bar
app.on('browser-window-created',function(e,window) {
  window.setMenu(null);
});

Also, please make this a Snap in the Ubuntu Store and also a .deb file.

**Comment by embbnux** [comment]
Thanks @yanike , will update it.
For Ubuntu Store, will investigate about it.

**Comment by embbnux** [comment]
hi @yanike We have supported snap in [0.1.4 release](https://github.com/ringcentral/ringcentral-embeddable-electron-app/releases/tag/v0.1.4)
