### ISSUE TITLE
create a rpm package

### ISSUE THREAD

**Issue by pstourac** [ringcentral/ringcentral-embeddable-electron-app#21]
Hi, please create an rpm package, as this app cannot be used on rpm based distros.

**Comment by embbnux** [comment]
Thanks @pstourac Will investigate on packaging rpm.

**Comment by embbnux** [comment]
hi @pstourac We have created a rpm package in https://github.com/ringcentral/ringcentral-embeddable-electron-app/releases/tag/v0.1.4
Can you help to test it on your linux os?

**Comment by pstourac** [comment]
Hello, thank you, package was succesfully installed on Fedora 32, application is running, give me few days to test funcionality.

**Comment by embbnux** [comment]
> Hello, thank you, package was succesfully installed on Fedora 32, application is running, give me few days to test funcionality.

Sure, thanks so much for it

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen it.
