### ISSUE TITLE
Minimize to Notification Area/Task Tray

### ISSUE THREAD

**Issue by Chankster** [ringcentral/ringcentral-embeddable-electron-app#3]
Would be nice to have the option to minimize to the notification area/task tray.

**Comment by docsmooth** [comment]
Check out the work in https://github.com/IsmaelMartinez/teams-for-linux for notifications in Electron apps, might be able to borrow

**Comment by embbnux** [comment]
Supported at [0.2.0](https://github.com/ringcentral/ringcentral-embeddable-electron-app/releases/tag/v0.2.0)
