### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by LarryStarr01** [ringcentral/ringcentral-embeddable-electron-app#32]
Installed the RPM, on pclinuxOS.
Received one error message from install.
"Error in file "/usr/share/applications/krita_jpeg.desktop": "jpeg/jfif" is an invalid MIME type ("jpeg" is an unregistered media type)"

Since the app installed I figured that was a problem with one of the icons.

Attempt to sign into Ringcentral get popup screen asking for verification code, received the email and entered the code, get the following:
![image](https://user-images.githubusercontent.com/77643172/104962284-ba950d00-599d-11eb-9864-6333c2eb6894.png)

**Comment by embbnux** [comment]
Sorry for missing this issue. Do you still have this issue now. And can you try to login here https://ringcentral.github.io/ringcentral-embeddable/

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
