### ISSUE TITLE
Please grant ringcentral embeddable to access your audio?

### ISSUE THREAD

**Issue by sbbaird** [ringcentral/ringcentral-embeddable-electron-app#33]
Easily installed but not able to use getting the following error....
"Please grant ringcentral embeddable to access your audio"
Linuxmint v 20

**Comment by embbnux** [comment]
Hi @sbbaird Do you get `Webphone Unavailable` in app. You need to click it to grant microphone permission.
And also please make sure that there are microphone devices in your computer.
This app need microphone and speaker for making and receiving calls

**Comment by calebott** [comment]
I'm getting the exact same issue. 

I never get a popup to grant permissions to my microphone.

Ubuntu 20.04.1 LTS 

![Selection_237](https://user-images.githubusercontent.com/53266287/106625433-41202180-653c-11eb-94dc-3e3724cdc3c2.png)

**Comment by embbnux** [comment]
@calebott can you help to check if there are microphone devices in your computer, and the microphone works for other software. The error also shows when there are not microphone devices.

**Comment by calebott** [comment]
@embbnux I have multiple microphones set up and I can make calls properly using the Ring Central website in my Chrome browser. I only have this issue on the embedded electron app.

**Comment by embbnux** [comment]
> @embbnux I have multiple microphones set up and I can make calls properly using the Ring Central website in my Chrome browser. I only have this issue on the embedded electron app.

Thanks so much for clarify. It seems that the electron version have issue at Ubuntu 20.04. Let me do more investigation.

**Comment by embbnux** [comment]
Reproduced in my side with snap installation. It seems that snap installation prevent to get microphone permission. Will investigate more.

**Comment by embbnux** [comment]
I think the root cause is that we publish snap package in [Strict](https://snapcraft.io/docs/snap-confinement#interfaces) mode. It works at Ubuntu 18 to get microphone permission. But fail at 20.
I will investigate more about how to get microphone permission with snap. For now, you can use dpkg package from [releases](https://github.com/ringcentral/ringcentral-embeddable-electron-app/releases)

**Comment by embbnux** [comment]
Hi @sbbaird @calebott  For snap user, after installation we need to connect microphone permission by [snap interface management](https://snapcraft.io/docs/interface-management):
```
$ sudo snap connect ringcentral-embeddable-voice:pulseaudio :pulseaudio
```
After running the command, reopen the app and it works with microphone.

**Comment by embbnux** [comment]
closed by inactive. Feel free to reopen it if you still have some issue.

**Comment by lonicerae** [comment]
Hello, this issue still persists on Fedora 32 with latest RPM ringcentral-embeddable-voice-app-0.1.6-1.x86_64. Any idea to troubleshoot? Thanks.

**Comment by embbnux** [comment]
> Hello, this issue still persists on Fedora 32 with latest RPM ringcentral-embeddable-voice-app-0.1.6-1.x86_64. Any idea to troubleshoot? Thanks.

Hi @lonicerae Can you try to install it with snap or use AppImage build? I don't have Fedora device now, so not sure how to give microphone permission to RPM package at Fedora.

This should be same issue as we have in snap package. We need user to add microphone permission for it manually.

**Comment by embbnux** [comment]
Hi @lonicerae From here https://discussion.fedoraproject.org/t/microphone-cannot-be-accessed-within-toolbox/19453/3 user need to install `alsa-plugins-pulseaudio` for rpm package

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
