### ISSUE TITLE
“Switch call to this device” not working

### ISSUE THREAD

**Issue by AdBeg** [ringcentral/ringcentral-embeddable-electron-app#36]
When an active call has been placed on hold I used to be able to use the “switch to this device” button from the “Active Calls” list to pick it up.  The button now doesn’t appear to do anything.  The “End Call” and “Transfer” buttons work fine though.  I tried updating to the latest version (released today) but the issue still persists.  Any ideas would be appreciated.

Cheers,

Adam

**Comment by embbnux** [comment]
Hi @AdBeg Thanks for reporting this. We have found the issue, will fix it soon

**Comment by AdBeg** [comment]
@embbnux that’s great news. Thank you so much. 👍

**Comment by embbnux** [comment]
@AdBeg It is fixed now. You need to reopen the app to make it load latest build.

**Comment by AdBeg** [comment]
Working perfectly.  Thank you :)

**Comment by embbnux** [comment]
> @embbnux Working perfectly. Thank you :)

You are welcome. Thanks so much for reporting this.
