### ISSUE TITLE
Option to join a meeting without logging in

### ISSUE THREAD

**Issue by toransahu** [ringcentral/ringcentral-embeddable-electron-app#4]
**New Feature Request:**

As we get an option on RingCentral's official apps for different platforms (e.g. Mac, Windows, Android, iPhone) to join the meeting via meeting invite URL **WITHOUT** login into the account, it would be great if we get the same option in this app also.

**Comment by embbnux** [comment]
Hi @toransahu, this is a good idea. Will investigate how to interact with RingCentral Meetings app.

**Comment by toransahu** [comment]
Thank for the consideration @embbnux :slightly_smiling_face:

**Comment by embbnux** [comment]
I am going to close this. For people who use RingCentral Video meeting, it is recommended to our RingCentral (Community) app. User don't need to login into meeting again with this app. 
https://github.com/ringcentral/ringcentral-community-app/
