### ISSUE TITLE
Meeting App does not work

### ISSUE THREAD

**Issue by dtantono** [ringcentral/ringcentral-embeddable-electron-app#44]
Hi
I got the Appimage app and the meeting link. But, when I want try to copy the meeting link on the app. But, instead it redirect me back to browser to join via web app. Is it a bug?
![2021-07-08_10-27_1](https://user-images.githubusercontent.com/29157187/124848315-907ce900-dfd7-11eb-951e-71efe73d4b42.png)

**Comment by embbnux** [comment]
Hi @dtantono currently the app doesn't support to run meeting in app. Users need to start or join meeting in Browser now

**Comment by dtantono** [comment]
I know ringcentral have a proprietary app on deb file. So, that means I need to use that app for a meeting. Is that so?

**Comment by embbnux** [comment]
> I know ringcentral have a proprietary app on deb file. So, that means I need to use that app for a meeting. Is that so?

Can you share the deb app? I am not sure about it.

**Comment by dtantono** [comment]
here it is https://support.ringcentral.com/download.html (https://downloads.ringcentral.com/RCM/RC/meetings/linux/RCMeetingsClientSetup.deb). Is that so?

**Comment by embbnux** [comment]
> here it is https://support.ringcentral.com/download.html (https://downloads.ringcentral.com/RCM/RC/meetings/linux/RCMeetingsClientSetup.deb). Is that so?

Yes, you can use this app to open RingCentral Meetings.

**Comment by dtantono** [comment]
Since there is a proprietary app that helps Linux users to use ringcentral service for join the meeting. I am just curious, What is this app for?

**Comment by embbnux** [comment]
> Since there is a proprietary app that helps Linux users to use ringcentral service for join the meeting. I am just curious, What is this app for?

This app is community version for RingCentral Phone at linux. For now, official RingCentral Phone doesn't support Linux.

**Comment by dtantono** [comment]
Well, I hope you can submit the request to ringcentral to expand their services and support to Linux as well

**Comment by embbnux** [comment]
> Well, I hope you can submit the request to ringcentral to expand their services and support to Linux as well

Sure, will feedback to PM team.

I will close this issue. Feel free to reopen it if you still need help.
