### ISSUE TITLE
Performance issues on Arch

### ISSUE THREAD

**Issue by jeffbeale** [ringcentral/ringcentral-embeddable-electron-app#45]
Currently running Manjaro (arch based distro), i7, 32gb of RAM on a dedicated gigabit ethernet connection. When running the Ringcentral phone app on my Windows laptop, I get only minor issues. Running the embeddable client installed via the AppImage, calls work great but I get the following issues:

- Constant re-registering of the phone with the server
- Lag from button press to actual response
- Constant freezing, then 'catching up' of the user interface
- Usually, but not always, reverts to the ongoing call screen when catching up and re-registering phone
- Whenever receiving a new call even while the GUI is frozen - the window will become highlighted, making it very difficult to do anything else while running the app

**Comment by embbnux** [comment]
Hi @unsaph3 Thanks for reporting this issue. Can you help to run the app in Debug mode and collect logs? Currently I don't have machine with Arch linux to test this.

To run in debug mode:

```
$ DEBUG=1 ./this_app_bin
```
And collect logs in opened developer tool.

**Comment by embbnux** [comment]
Hi @unsaph3 which desktop environment are you using? I am trying to download Manjaro in virtualbox to test.

**Comment by unsaph3** [comment]
I'm so sorry about the slow replies. I use Manjaro with KDE. As far as running the phone to debug, let me attempt to do it for a bit this morning. How long of a time frame do you need logs collected to show these kinds of issues?

**Comment by unsaph3** [comment]
I am trying to start the debug session, and this one is stumping me. Here's the terminal output:
![image](https://user-images.githubusercontent.com/72213598/128370363-65ab4cf9-e003-4479-8ef5-d15b11f7f7cc.png)
It does not look like the snap installed the file in my home folder, even among the hidden files.

**Comment by embbnux** [comment]
@jeffbeale if you install from snap, the bin file is in `/snap/ringcentral-embeddable-voice/current`. And just need logs from you start app and get the issue.
And Which one you use for installing this package, snap or AppImage?

**Comment by jeffbeale** [comment]
```
DEBUG=1 ./snap/ringcentral-embeddable-voice/current
BASH ./current is a directory.
```
I've tried running it within the `ringcentral embeddable` directory, within the `current` directory, same output. Can you type out the full command with the directory that needs to be run (Google is not helping me get the correct syntax for the DEBUG command)

**Comment by embbnux** [comment]
> ```
> DEBUG=1 ./snap/ringcentral-embeddable-voice/current
> BASH ./current is a directory.
> ```
> 
> I've tried running it within the `ringcentral embeddable` directory, within the `current` directory, same output. Can you type out the full command with the directory that needs to be run (Google is not helping me get the correct syntax for the DEBUG command)

You can run with:
```
$ DEBUG=1 /snap/ringcentral-embeddable-voice/current/ringcentral-embeddable-voice
```

**Comment by jeffbeale** [comment]
```
[prizmo@communistrobot ~]$ DEBUG=1 /snap/ringcentral-embeddable-voice/current/ringcentral-embeddable-voice
bash: /snap/ringcentral-embeddable-voice/current/ringcentral-embeddable-voice: No such file or directory
[prizmo@communistrobot ~]$ 
```

**Comment by embbnux** [comment]
> ```
> [prizmo@communistrobot ~]$ DEBUG=1 /snap/ringcentral-embeddable-voice/current/ringcentral-embeddable-voice
> bash: /snap/ringcentral-embeddable-voice/current/ringcentral-embeddable-voice: No such file or directory
> [prizmo@communistrobot ~]$ 
> ```

It seems your snap installation path is different as mime.  Anyway, I have downloaded  Manjaro, let me try in my side.

**Comment by embbnux** [comment]
hi @jeffbeale Can you share more about your Manjaro version,  Graphics and driver.
At my test, it works well with Memory 4096, Video Memory 128. And in VirtualBox, it can reproduce performance issue if I select wrong Graphics Controller.
And it is appreciated if you can provide a video about this issue.  You can send it by https://developers.ringcentral.com/support/create-case

**Comment by jeffbeale** [comment]
Manjaro version: 21.1.0rc4
Graphics: Onboard Intel Graphics (I run a Skullcandy i7 NUC with 32gb RAM)
I'll grab some video with OBS tomorrow and upload it - work has shut down their RC access for the night.

Thanks for following up on this

**Comment by jeffbeale** [comment]
Of course when trying to reproduce the issue on my machine, it now seems to work fine. I'll keep using it and if I am able to capture video of it during this coming week, I'll upload it via the portal you posted. If 1 week goes by and I haven't been able to reproduce this, go ahead and close the issue out

**Comment by embbnux** [comment]
@jeffbeale Thanks for confirming this. Look forward to your message.

**Comment by jeffbeale** [comment]
Closing this issue. I suspect the majority of the issues I am having with RC is that our managers have 20+ people logged into the same account and it's just not designed for that use case.
