### ISSUE TITLE
Cannot login in Ubuntu 20.04

### ISSUE THREAD

**Issue by pwhipp** [ringcentral/ringcentral-embeddable-electron-app#52]
Installed the snap. 
On sign in it tells me it does not recognise the email address.
Tried using the google account with the email address to but that said it was not a recognised account.

I can log in using the email address on the android app.

I can log in and use the ringcentral app in chrome on the linux desktop (which is what I have to do until this issue is resolved).

**Comment by pwhipp** [comment]
I deleted the ringcentral cache btw and that made no difference.

**Comment by embbnux** [comment]
Hi @pwhipp  Can you help to check following information:

Does your RingCentral account from RingCentral Partner brand? which brand?

Did you set Environment data in this app previously? 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/7036536/159612444-fffd0444-146f-46f6-b2ae-832778ec2221.png">

And can you share screenshot of the login window that showing the error?

**Comment by embbnux** [comment]
hi @pwhipp Can you help to try if you can login with 0.2.1? We released 0.2.1 to support RingCentral parter branding accounts.

**Comment by embbnux** [comment]
I am going to close this by inactive. Feel free to reopen it if you still have same issue.
