### ISSUE TITLE
Users hidden from Company Directory shown in Contacts in ringcentral-embeddable-electron-app

### ISSUE THREAD

**Issue by lmf-mx** [ringcentral/ringcentral-embeddable-electron-app#58]
Using the AppImage, v0.2.1. 2 users hidden from the Company Directory per https://support.ringcentral.com/app/admin/desktop-web/managing-company-directory-ringcentral-online-account.html do not show in Glip, but appear in this app.

**Comment by embbnux** [comment]
Hi @lmf-mx It is supported now. You should get that after reopening the app. The data may have some cache, you can re-login to clear all cache.
