### ISSUE TITLE
Ctrl-Q shortcut 'stolen' by the application

### ISSUE THREAD

**Issue by godlike64** [ringcentral/ringcentral-embeddable-electron-app#59]
The Ctrl-Q shortcut to quit the application added in 0.2.0 appears to be 'stolen' by RingCentral: I can quit RingCentral when it is out of focus, and even on a different virtual desktop. Whenever I press 'Ctrl-Q', RingCentral will be the first thing to close, no matter how many windows I have opened and focused.

OS: Linux
RingCentral version: 0.2.1

**Comment by embbnux** [comment]
Hi @godlike64 Thank for feedback this. Yes, it should only work when focus at the app. Let me track how to fix this.

**Comment by embbnux** [comment]
Hi @godlike64 released 0.2.2 to fix this

**Comment by embbnux** [comment]
I am going to close this. Feel free to reopen it if you still have same issue.
