### ISSUE TITLE
App uses wrong window manager

### ISSUE THREAD

**Issue by mjg0** [ringcentral/ringcentral-embeddable-electron-app#62]
The app uses its own window manager rather than the one provided by the desktop environment; it would be nice to at least have the option of using my window manager, which is much more feature-rich. It's a bit of an annoyance on KDE, and I imagine it would be worse with tiling window managers.

**Comment by embbnux** [comment]
Hi @mjg0 do you mean this header? 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/7036536/174518929-95455823-95c6-4838-98d8-bcd8b04029a8.png">

**Comment by embbnux** [comment]
okay, thanks for confirming. Native header is hidden by the app. Let me add a option to use native header.

**Comment by embbnux** [comment]
Supported at 0.2.3
