### ISSUE TITLE
Sign-In

### ISSUE THREAD

**Issue by burnseysr** [ringcentral/ringcentral-embeddable-electron-app#73]
Every time I select google to sign-in the Ring Central the sign-in doesn't recognize my Google credentials.

![image](https://github.com/ringcentral/ringcentral-embeddable-electron-app/assets/52325070/e67d7d60-b7b4-4442-a734-ae3f2b5d87f4)

**Comment by embbnux** [comment]
Hi @burnseysr Google account has personal and business account? Can you check if you select wrong type at google login?

**Comment by embbnux** [comment]
Closed by inactive. Feel free to reopen it.
