### ISSUE TITLE
When receiving calls, there's 50% chance that I won't be able to hear that person while they can hear me

### ISSUE THREAD

**Issue by john241215** [ringcentral/ringcentral-embeddable-electron-app#87]
When calling someone, I can always hear that person, and that person can hear me.
But when receiving calls, some are miss or hit. And when it's a hit, they can hear me, but I can't hear them.

Using the latest version of .deb 
Same thing happens when using the extension (firefox)

I'm on LM 21.3

Thank you so much!

**Comment by embbnux** [comment]
hi @john241215 do you use RingCentral for Firefox browser extension? this project is for desktop app.

**Comment by john241215** [comment]
Thank you so much!
I'll test it for a few days and report back here.

**Comment by john241215** [comment]
Yep, it has happened once to me while using that web app.

**Comment by embbnux** [comment]
Closed this as this is not issue belongs to this app, it also happens on web app.
